// THIS FILE IS AUTOGENERATED. DO NOT EDIT
/* eslint-disable */
/* tslint:disable */
export const noop = () => {}
import * as PeopleSearchPage copy from './PeopleSearchPage copy'
export { PeopleSearchPage copy }