export const layout: string;
export const toolbarLayout: string;
export const toolbarItem: string;
export const quickPriceLayout: string;
export const quickPriceItem: string;
export const iconButton: string;
export const packageSeparator: string;
export const bookSearchResult: string;
export const bookSearchThumbnail: string;
