export declare const bookSearchResult: string
export declare const bookSearchThumbnail: string
export declare const icon: string
export declare const layout: string
export declare const packageSeparator: string
export declare const quickPriceItem: string
export declare const quickPriceLayout: string
export declare const tableSearch: string
export declare const toolbarItem: string
export declare const toolbarLayout: string
export declare const toolbarSearch: string
